/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public void helloWorld() {
    	System.out.println("Hello World");
    }
}
